apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cslb-lookup.fullname" . }}
  labels:
    {{- include "cslb-lookup.labels" . | nindent 4 }}
data:
  DATA_SOURCE: {{ .Values.config.dataSource | quote }}
  DATABASE_PATH: {{ .Values.config.databasePath | quote }}
