{{- if .Values.secrets.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cslb-lookup.fullname" . }}
  labels:
    {{- include "cslb-lookup.labels" . | nindent 4 }}
type: Opaque
data:
  API_KEY: {{ .Values.secrets.apiKey | b64enc | quote }}
{{- end }}
