{{- if or .Values.secrets.firecrawlApiKey .Values.secrets.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cslb-lookup.fullname" . }}
  labels:
    {{- include "cslb-lookup.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.apiKey }}
  API_KEY: {{ .Values.secrets.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.firecrawlApiKey }}
  FIRECRAWL_API_KEY: {{ .Values.secrets.firecrawlApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
