CLASSIFICATIONS: dict[str, str] = {
    "A": "General Engineering Contractor",
    "B": "General Building Contractor",
    "C-2": "Insulation and Acoustical Contractor",
    "C-4": "Boiler, Hot Water Heating and Steam Fitting Contractor",
    "C-5": "Framing and Rough Carpentry Contractor",
    "C-6": "Cabinet, Millwork and Finish Carpentry Contractor",
    "C-7": "Low Voltage Systems Contractor",
    "C-8": "Concrete Contractor",
    "C-9": "Drywall Contractor",
    "C10": "Electrical Contractor",
    "C11": "Elevator Contractor",
    "C12": "Earthwork and Paving Contractor",
    "C13": "Fencing Contractor",
    "C15": "Flooring and Floor Covering Contractor",
    "C16": "Fire Protection Contractor",
    "C17": "Glazing Contractor",
    "C20": "Warm-Air Heating, Ventilating and Air-Conditioning Contractor",
    "C21": "Building Moving/Demolition Contractor",
    "C22": "Asbestos Abatement Contractor",
    "C23": "Ornamental Metal Contractor",
    "C27": "Landscaping Contractor",
    "C28": "Lock and Security Equipment Contractor",
    "C29": "Masonry Contractor",
    "C31": "Construction Zone Traffic Control Contractor",
    "C32": "Parking and Highway Improvement Contractor",
    "C33": "Painting and Decorating Contractor",
    "C34": "Pipeline Contractor",
    "C35": "Lathing and Plastering Contractor",
    "C36": "Plumbing Contractor",
    "C38": "Refrigeration Contractor",
    "C39": "Roofing Contractor",
    "C42": "Sanitation System Contractor",
    "C43": "Sheet Metal Contractor",
    "C45": "Electrical Sign Contractor",
    "C46": "Solar Contractor",
    "C47": "General Manufactured Housing Contractor",
    "C50": "Reinforcing Steel Contractor",
    "C51": "Structural Steel Contractor",
    "C53": "Swimming Pool Contractor",
    "C54": "Ceramic and Mosaic Tile Contractor",
    "C55": "Water Conditioning Contractor",
    "C57": "Well Drilling Contractor",
    "C60": "Welding Contractor",
    "C61": "Limited Specialty",
    "D3": "Awnings",
    "D4": "Central Vacuum Systems",
    "D6": "Concrete Related Services",
    "D9": "Drilling, Blasting and Oil Field Work",
    "D10": "Elevated Floors",
    "D12": "Synthetic Products",
    "D16": "Hardware, Locks and Safes",
    "D21": "Machinery and Pumps",
    "D24": "Metal Products",
    "D28": "Doors, Gates and Activating Devices",
    "D30": "Pile Driving and Pressure Foundation Jacking",
    "D31": "Pole Installation and Maintenance",
    "D34": "Prefabricated Equipment",
    "D35": "Pool and Spa Maintenance",
    "D38": "Sand and Water Blasting",
    "D39": "Scaffolding",
    "D40": "Service Station Equipment and Maintenance",
    "D41": "Siding and Decking",
    "D42": "Non-Electrical Sign Installation",
    "D49": "Tree Service",
    "D50": "Suspended Ceilings",
    "D52": "Window Coverings",
    "D56": "Trenching",
    "D62": "Air and Water Balancing",
    "D63": "Construction Clean-Up",
    "D64": "Non-Specialized",
    "D65": "Weatherization and Energy Conservation",
    "HAZ": "Hazardous Substance Removal Certification",
    "ASB": "Asbestos Certification",
}


def get_classification_description(code: str) -> str:
    return CLASSIFICATIONS.get(code, "Unknown Classification")
