{{- if .Values.secrets.firecrawlApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cslb-license-api.fullname" . }}
  labels:
    {{- include "cslb-license-api.labels" . | nindent 4 }}
type: Opaque
data:
  FIRECRAWL_API_KEY: {{ .Values.secrets.firecrawlApiKey | b64enc | quote }}
{{- end }}
